# .streamlit/config.toml

[theme]
base = "light" # Ou "dark" - este é o tema base do Streamlit
primaryColor = "#FF4B4B" # Seus estilos CSS podem referenciar ou complementar esta cor
# backgroundColor = ... (você está controlando isso via CSS agora)
# secondaryBackgroundColor = ...
# textColor = ...
font = "sans serif"

[client]
showFooter = false
toolbarMode = "minimal" # Esconde "Deploy app", etc.

[logger]
level = "INFO"

[runner]
gatherUsageStats = false